config/routes.rb
Rails.application.routes.draw do
  get 'formes/index'
  get 'formes/new'
  get 'formes/create'
  get 'formes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :formes, only: [:index, :new, :create, :destroy]   
  root "formes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forme.rb
class Forme < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
   validates :title, :category, :price, :year, presence: true # Make sure the owner's name is present.   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/formes_controller.rb
class FormesController < ApplicationController   
  def index   
     @formes = Forme.all   
  end   
     
  def new   
     @forme = Forme.new   
  end   
     
  def create   
     @forme = Forme.new(forme_params)   
        
     if @forme.save   
        redirect_to formes_path, notice: "Successfully uploaded."   
     else   
        render "new"   
     end   
        
  end   
     
  def destroy   
     @forme = Forme.find(params[:id])   
     @forme.destroy   
     redirect_to formes_path, notice:  "Successfully deleted."   
  end   
     
  private   
     def forme_params   
     params.require(:forme).permit(:title, :category, :price, :year, :attachment)   
  end   
     
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formes_helper.rb
module FormesHelper
end

app/views/formes/create.html.erb
<h1>Formes#create</h1>
<p>Find me in app/views/formes/create.html.erb</p>

app/views/formes/destroy.html.erb
<h1>Formes#destroy</h1>
<p>Find me in app/views/formes/destroy.html.erb</p>

app/views/formes/index.html.erb
<marquee direction="right"> <center> <h1> JORAH GARRERY COMPANY </h1> </center></marquee>
<style>
h1{
  color: blue;

}
h2{
  color: black;

}
h4{
  color:red;
}
.card-img-top
{
   height:200px;
   width:200px;
}
body{
  background color:grey;
}
footer{
    background: grey;
    padding: 25px;

}
footer p{
    text-align: center;
    color: #fff;
}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
</style>


<strong><center><h2>FILMS </h2></center></strong>
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  
<center><b><u><h4><%= link_to "New Forme", new_forme_path %></h4></u></b></center>  
<br>   
<br>   

<div class="album py-5 bg-light">
        <div class="container">
        <div class="row">
 <% @formes.each do |forme| %> 
          
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="<%= forme.attachment %>" class="card-img-top"  alt="Card image cap">
                <div class="card-body">
                  <p class="card-text"><b>Title:</b><%= forme.title %><br><b>category:</b><%= forme.category %><br><b>Year:</b><%= forme.year %><br><b>price:</b><%= forme.price %></p>
                  <b><u><%= link_to "Download", forme.attachment_url %></b></u>
                  <b><u><%= link_to "Delete",  forme, method: :delete, confirm: "Are you sure you want to delete #{forme.attachment}?" %>
                  </b></u>
                  </div>
                </div>
              </div>
              <% end %> 
            </div>
            <br>
            <br>
            <footer>
      
            <p>&copy; Information Technology- 2018</p>
    </footer>

app/views/formes/new.html.erb
  
   <%= form_for @forme, html: { multipart: true } do |f| %>   
      <%= f.label :title %>   
      <%= f.text_field :title %>   
      <%= f.label :category %>   
      <%= f.text_field :category %>  
      <%= f.label :price %>   
      <%= f.text_field :price %>
      <%= f.label :year %>   
      <%= f.text_field :year %>    
      <br><br>   
      <%= f.label :attachment %>   
      <%= f.file_field :attachment %>   
      <br>   
      <%= f.submit "Save" %>   
   <% end %>   
</div>   
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>   
<html>   
 <head>   
      <title>File Uploading</title>   
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
      <%= csrf_meta_tags %>   
   </head>   
      
   <body>   
      <div>   
         <%= yield %>   
      </div>   
   </body>   
</html>  